import type { CanvasObjectBase } from "../../core/document/model";

export type SpriteOverlayDisplayMode = "focus" | "cutEdit" | "gridEdit" | "audit" | "debug";
export type CanvasSpriteOverlaySettings = {
  displayMode: SpriteOverlayDisplayMode;
  showBounds: boolean;
  showLabels: boolean;
  selectedOnly: boolean;
  showSubgrids: boolean;
  showExactFrames: boolean;
};
export type SpriteFrameSourceKind = "grid" | "stackframe" | "exact" | "manual" | "unknown";
export type SpriteStackframeDirection = "vertical" | "horizontal";
export type CanvasSpriteStackframe = {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  count: number;
  direction: SpriteStackframeDirection;
  step: number;
  labels?: readonly string[];
  spriteId?: string;
  animationId?: string;
  row?: number;
  column?: number;
  description?: string;
};
export type CanvasSpriteSubgridRegion = {
  kind: "spriteSubgridRegion";
  id: string;
  x: number;
  y: number;
  columns: number;
  rows: number;
  cellWidth: number;
  cellHeight: number;
  width: number;
  height: number;
  source?: "spriteforgeGrid" | "roughCutGrid" | "derived" | "manual";
  gridKind?: string;
  framePrefix?: string;
  frameStartIndex?: number;
  frameLabels?: readonly string[];
  pivot?: string;
};
export type CanvasSpriteGridSpec = CanvasSpriteSubgridRegion;
export type CanvasSpriteFrame = {
  id: string;
  label: string;
  spriteId?: string;
  animationId?: string;
  clipId?: string;
  kind?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  row?: number;
  column?: number;
  source?: "grid" | "frame" | "inline";
  gridId?: string;
  sourceKind?: SpriteFrameSourceKind;
  sourceGridId?: string;
  sourceRow?: number;
  sourceColumn?: number;
  sourceFrameId?: string;
  sourceStackframeId?: string;
  sourceStackIndex?: number;
  pivot?: string;
};
export type CanvasSpriteAnimation = {
  id: string;
  spriteId: string;
  gridId?: string;
  row?: number;
  frameIds: readonly string[];
  fps?: number;
  loop?: boolean;
};
export type CanvasSpriteDiagnostics = {
  severity: "info" | "warning";
  code: string;
  message: string;
  frameIds?: readonly string[];
};
export type CanvasSpriteSpec = {
  id: string;
  name: string;
  dialect: "sprite" | "spriteforge";
  targetId?: string;
  sourceName?: string;
  atlasImage?: string;
  atlasWidth?: number;
  atlasHeight?: number;
  grids: readonly CanvasSpriteGridSpec[];
  stackframes: readonly CanvasSpriteStackframe[];
  frames: readonly CanvasSpriteFrame[];
  animations: readonly CanvasSpriteAnimation[];
  diagnostics: readonly CanvasSpriteDiagnostics[];
  overlay: CanvasSpriteOverlaySettings;
  selectedFrameId?: string;
  rawToml?: string;
};
export type SpriteSidecarObject = CanvasObjectBase<"spriteSidecar"> & {
  role?: "spriteSidecar";
  targetId?: string;
  spec: CanvasSpriteSpec;
};
export type SpriteCanvasObject = SpriteSidecarObject;
